### ISSUE TITLE
No output when compiling a directory

### ISSUE THREAD

**Issue by Yaojian** [swc-project/cli#27] opened 2021-05-24 07:58 UTC
### For a project

```
<ProjectRoot>
+-- src
    +-- index.ts
```
and
```
@swc/cli: 0.1.42
@swc/core: 1.2.58
```
### Nothing generated when compiling a directory

The command
```
npx swc src -d dist
```
only creates an empty directory `<ProjectRoot>/dist` **without**  `dist/index.ts`.

* same behavior with/without `.swcrc`
* It seems that ` await util.globSources(cliOptions.filenames, cliOptions.includeDotfiles)` returns an empty object: `{}`

### Output generated as expected when compiling a single file
```
npx swc src\index.ts -d dist
```
generates the `dist/index.ts`

**Comment by kdy1** [comment] 2021-05-24 07:59
Can you try `@swc/cli: 0.1.41`? Recently there were some changes.

**Comment by Yaojian** [comment] 2021-05-24 08:04
`@swc/cli: 0.1.41` does generate `index.js` when executing `swc src -d dist`.

**Comment by kdy1** [comment] 2021-05-24 08:06
Thanks! I'll revert and publish a new version.

**Comment by kdy1** [comment] 2021-05-24 08:08
I published a new version

**Comment by chyzwar** [comment] 2021-05-25 06:43
@Yaojian What version of node do you use and what is you OS ?

**Comment by chyzwar** [comment] 2021-05-25 07:30
@kdy1  can we keep it open issue. I would like to investigate and find fix.

**Comment by Lodin** [comment] 2021-05-26 03:16
@chyzwar, I guess it is Windows. I faced the same issue yesterday with `0.1.42`. The root of the issue is that both `glob` and `fast-glob` cannot work with the Windows-like paths, and in the code there is a missed `slash` call for the glob expression. Created PR to fix the issue.

**Comment by chyzwar** [comment] 2021-05-26 15:26
@Lodin thanks, I will bring back fast-glob branch and test on windows. In my integration branch I will try to create test for window

**Comment by chyzwar** [comment] 2021-05-30 08:20
This should now be fixed in latest version of cli.

**Comment by kdy1** [comment] 2021-05-30 08:31
Thanks!

**Closed by kdy1** 2021-05-30 08:31 UTC
